import type { Experience } from "./types";
export const experienceData: Experience[] = [
  { title: "GIANTS Birthday Experience", description: "A high-energy birthday concept combining basketball, movement games, team challenges, music, and unforgettable GIANTS moments.", tags: ["Birthday", "Basketball", "Team Games"], featured: true, includes: ["Birthday game flow", "Basketball-inspired challenges", "Team wars & mini competitions", "MVP moment / birthday spotlight", "Optional flyer and theme concept"], offer: ["Custom offer based on duration, location, theme, and group size", "Trial birthday experience available"] },
  { title: "Functional Movement Experience", description: "High-energy movement experiences focused on strength, conditioning, mobility, rhythm, and confidence.", tags: ["Movement", "Energy", "Wellbeing"], includes: ["Full-body movement", "Mobility & endurance", "Group energy", "Team-based challenges"], offer: ["Group experiences: from €10–€15 per person", "Private coaching: from €30", "Monthly access: available on request"] },
  { title: "Basketball Experience", description: "Skill-focused basketball experiences built around ball handling, shooting, game situations, confidence, and team energy.", tags: ["Basketball", "Skills", "Teamwork"], includes: ["Technical drills", "Game situations", "Speed & agility work", "Confidence-building challenges"], offer: ["Group experiences: from €12–€20 per person", "Private training: from €30", "Team experiences: custom offer"] },
  { title: "Team Experience Events", description: "Interactive group experiences using movement challenges, teamwork missions, and competitive energy to build trust and connection.", tags: ["Corporate", "Teams", "Challenges"], includes: ["Team challenges", "Leadership exercises", "Communication games", "Fun competitive activities"], offer: ["Corporate and group packages available on request", "Pricing depends on duration, format, and group size"] },
  { title: "Youth Basketball Bootcamp", description: "A structured youth experience focused on fundamentals, confidence, discipline, teamwork, and enjoyment of the game.", tags: ["Youth", "Basketball", "Confidence"], includes: ["Daily skill development", "Fun competitions", "Team games", "Discipline & teamwork"], offer: ["Weekly camp: from €40–€150 per child", "Final price depends on duration and program format"] },
  { title: "Community Sport Events", description: "Organized sport and culture experiences combining basketball, music, food, games, and community connection.", tags: ["Community", "Events", "Culture"], includes: ["Open workouts", "Basketball games", "Social experiences"], offer: ["Community entry: from €5–€15", "Private event hosting: custom offer"] },
];
